services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: protonvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports: # These are the qBittorrent ports, I like to use random ports and not the default ports 49152
      - 49893:49893 # This is for the qBittorrent WebUI Port
      - 6881:6881 # Listening port for TCP
      - 6881:6881/udp # Listening port for UDP
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=X503U0DXDLC5r64S+pmp                        
      - OPENVPN_PASSWORD=UYGveoXXpa2PQMevfEPiCCGFK80LKoKT              
      - VPN_PORT_FORWARDING=on
      - SERVER_COUNTRIES=Netherlands,Germany # The server countries we'll use. They have to be P2P
    volumes:
      - ./config:/gluetun
    restart: unless-stopped
