---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/hdd/media/sonarr_config:/config
      - /mnt/hdd/media/tvseries:/tv #optional
      - /mnt/hdd/media/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped