---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - VERSION=docker
    volumes:
      - /mnt/hdd/media/library:/config
      - /mnt/hdd/media/tvseries:/tv
      - /mnt/hdd/media/movies:/movies
    restart: unless-stopped