services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000 # to find your current ID just type "id" in the terminal
      - PGID=1000 # to find your current group ID just type "id" in the terminal
      - TZ=Europe/London
      - WEBUI_PORT=49893 # This needs to be the exact same port we used on glueton for the WebUI
      - TORRENTING_PORT=6881
    volumes:
      - ./config:/config # this will create the config folder in the same folder as we have the yml file
      - /mnt/hdd/media/downloads:/downloads # change the left part of : to your actual path where you want to store your downloads
    network_mode: "container:protonvpn" # this needs to be the exact same name as the protonvpn container we defined
    restart: unless-stopped